markdown: kramdown
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: noifniof3nioaniof3nioafafinoafnoif
exclude: [node_modules,bower_components,css,img,js,old,scss,.git,.sass-cache]

gauges_id: 503c5af6613f5d0f19000027
google_analytics_id: UA-50755011-1

repository: https://github.com/jekyll/jekyll
help_url: https://github.com/jekyll/jekyll-help

collections:
  docs:
    output: true